defaults:
  - shared

wandb:
  name: large
dataset:
  num_frames: 8
  spacing: 4
data_loader:
  batch_size: 12
model:
  mixing: 0.0
  fake_pair: true
augmentation:
  enabled: true
discriminator:
  base_channels: 32768
  max_channels: 1024
  keypoint_mapping: true
  keypoint_heatmaps: true
generator:
  keypoint_embed_dim: 512
  base_channels: 32768
  max_channels: 1024
  spatial_noise: false
  keypoint_heatmaps: true
