defaults:
  - shared

wandb:
  name: large-no-mixing
dataset:
  num_frames: 1
  spacing: 1
data_loader:
  batch_size: 12
model:
  mixing: 0.0
  fake_pair: false
augmentation:
  enabled: true
discriminator:
  base_channels: 32768
  max_channels: 1024
  keypoint_mapping: false
  keypoint_heatmaps: false
generator:
  keypoint_embed_dim: 0
  base_channels: 32768
  max_channels: 1024
  spatial_noise: false
  keypoint_heatmaps: false
