defaults:
  - shared

wandb:
  name: no_temporal
dataset:
  num_frames: 1
  spacing: 1
data_loader:
  batch_size: 8
model:
  mixing: 0.0
  fake_pair: true
augmentation:
  enabled: true
discriminator:
  base_channels: 16384
  max_channels: 512
  keypoint_mapping: true
  keypoint_heatmaps: true
generator:
  keypoint_embed_dim: 512
  base_channels: 16384
  max_channels: 512
  spatial_noise: false
  keypoint_heatmaps: true
